### ISSUE TITLE
sh: 0: Can't open /var/www/scripts/bin/xdebug_disable.sh

### ISSUE THREAD

**Issue by langert** [dockware/examples#6]
Hi,
running docker-compose up -d does not start the container because of

sh: 0: Can't open /var/www/scripts/bin/xdebug_disable.sh

Are there some files missing in dockware/dev:latest?
Thx for any hint
Timo

**Comment by boxblinkracer** [comment]
hi
oh just saw this sorry
i think this is already fixed by now right :)
